name = "station-noor"
main = "src/worker.js"
compatibility_date = "2025-03-15"
workers_dev = true
preview_urls = true

[[routes]]
pattern = "*.noorstations.com/*"
zone_name = "noorstations.com"

[build]
upload = { 
  format = "service-worker",
  main = "src/worker.js"
}

[env.production]
workers_dev = false
